apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sensor-demo
  template:
    metadata:
      labels:
        app: sensor-demo
    spec:
      containers:
      - name: sensor-demo
        image: spindle
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
